### ISSUE TITLE
determine 获取accessToken存在bug

### ISSUE THREAD

**Issue by oulp** [node-weixin/node-weixin-auth#2]
node-weixin-jssdk 调用prepare时，首次会报如下错误，后面才可以
``
{ errcode: 41001,
  errmsg: 'access_token missing hint: [N3rbDA0024shc1!]'
 }
``

**Comment by calidion** [comment]
不知道你说的是什么bug。

请详细描述。

如果能提供测试结果与修复代码是最好的。

**Comment by oulp** [comment]
@calidion 已修改描述

**Comment by oulp** [comment]
找到问题了，您代码里获取accessToken失败没提示，且直接赋值null，导致我后面的操作都是失败的。

`
_onRequest: function (settings, app, cb) {
    var self = this;
    return function (error, json) {
      settings.get(app.id, 'auth', function (auth) {
        auth = auth || {};
        if (error) {
          auth.accessToken = null;
        } else {
          auth.accessToken = json.access_token;
        }
        settings.set(app.id, 'auth', auth, function () {
          if (self.onAccessToken) {
            self.onAccessToken(app, auth);
          }
          cb(error, json);
        });
      });
    };
  },
`

**Comment by calidion** [comment]
你不判断callback的error吗？

**Comment by oulp** [comment]
哦，那不是您的问题了，是"node-weixin-jssdk"里的prepare没判断。

**Comment by calidion** [comment]
OK。那关掉了。
